### PR TITLE
added dark mode support #5

### PR DESCRIPTION
**Pull request by Bhargavaansh2211**
#5 added feature of dark mode
Dark mode support added , the theme is set automatically based on the theme user is using on the system.
The themeMode property determines which theme mode to use which is initialized as ThemeMode.system.
ThemeMode.system follows the system-wide theme setting of the device. If the system is set to light mode, the app will use the light theme, and if it's set to dark mode, the app will use the dark theme.
Screenshot 2024-03-17 210010

### CODE REVIEW

**Comment by Illuminati9** [comment]
@Bhargavaansh2211 , can you add toggle button so that user can change it accordingly

**Comment by Bhargavaansh2211** [comment]
@Illuminati9 , Sorry I am not able to do so. Does this work as isssue mention switching either based on toggle switch or automatic detection ?

**Comment by Illuminati9** [comment]
Both works but try to make both like try to add toggle button

**Comment by Bhargavaansh2211** [comment]
added toggle button but it is not able to switch between modes

**Comment by Illuminati9** [comment]
@Bhargavaansh2211 , no problem but try to do it in future but for now I am accepting your pr

**Pull request closed without merging**
