### PR TITLE
update the app icon sucessfully

### PR DESCRIPTION
**Pull request by RISHABHKUSHWAHA7**
update the icon by a flutter  dependencies

### CODE REVIEW

**Comment by Illuminati9** [comment]
@RISHABHKUSHWAHA7 , can you share screenshots of changes

**Comment by RISHABHKUSHWAHA7** [comment]
ok sir

**Comment by RISHABHKUSHWAHA7** [comment]
icon

**Comment by Illuminati9** [comment]
@RISHABHKUSHWAHA7 , LGTM

**Pull request closed without merging**
